### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by crypt47** [mattmacy/networking#26]
Hi, I'm experiencing an error like this on FreeBSD 12 RC-1, default setup afaik:

f12 src # make buildworld
...
--------------------------------------------------------------
>>> stage 1.2: bootstrap tools
--------------------------------------------------------------
cd /usr/src; INSTALL="sh /usr/src/tools/install.sh"  TOOLS_PREFIX=/usr/obj/usr/src/amd64.amd64/tmp  PATH=/usr/obj/usr/src/amd64.amd64/tmp/legacy/usr/sbin:/usr/obj/usr/src/amd64.amd64/tmp/legacy/usr/bin:/usr/obj/usr/src/amd64.amd64/tmp/legacy/bin:/sbin:/bin:/usr/sbin:/usr/bin  WORLDTMP=/usr/obj/usr/src/amd64.amd64/tmp  MAKEFLAGS="-m /usr/src/tools/build/mk  -m /usr/src/share/mk" make  -f Makefile.inc1  DESTDIR=  OBJTOP='/usr/obj/usr/src/amd64.amd64/tmp/obj-tools'  OBJROOT='${OBJTOP}/'  MAKEOBJDIRPREFIX=  BOOTSTRAPPING=1200086  BWPHASE=bootstrap-tools  SSP_CFLAGS=  MK_HTML=no NO_LINT=yes MK_MAN=no  -DNO_PIC MK_PROFILE=no -DNO_SHARED  -DNO_CPU_CFLAGS MK_WARNS=no MK_CTF=no  MK_CLANG_EXTRAS=no MK_CLANG_FULL=no  MK_LLDB=no MK_TESTS=no  MK_INCLUDES=yes MK_LLVM_TARGET_ALL=no bootstrap-tools
===> lib/clang/libllvmminimal (obj,all,install)
[Creating objdir /usr/obj/usr/src/amd64.amd64/tmp/obj-tools/lib/clang/libllvmminimal...]
[Creating nested objdir /usr/obj/usr/src/amd64.amd64/tmp/obj-tools/lib/clang/libllvmminimal/Support...]
[Creating nested objdir /usr/obj/usr/src/amd64.amd64/tmp/obj-tools/lib/clang/libllvmminimal/TableGen...]
c++    -std=c++11 -fno-exceptions -fno-rtti -gline-tables-only -stdlib=libc++ -Wno-c++11-extensions  -c /usr/src/contrib/llvm/lib/Support/APFloat.cpp -o Support/APFloat.o
/usr/src/contrib/llvm/lib/Support/APFloat.cpp:15:10: fatal error: 'llvm/ADT/APFloat.h' file not found
#include "llvm/ADT/APFloat.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[3]: stopped in /usr/src/lib/clang/libllvmminimal
*** Error code 1

I'm new to building freebsd's world, so this may be something obvious. Also some folk says native ZFS encryption will come wth FreeBSD's release. How true is this?

**Comment by mattmacy** [comment]
Sorry I missed this I didn't expect an issue filed on a private fork.
The branch off 9-14 HEAD that has zfs crypto support is `projects/zfs-crypto-merge-0914`. That may end up being abandoned with simply adopting ZoL features wholesale:
https://github.com/zfsonfreebsd/ZoF
user land uses autoconf + gmake, kernel module build is `make -f Makefile.bsd` in ZoF/module

User land works fully and ztest passes. However, one must make sure that one doesn't have any old libaries or commands installed.

The module is currently not stable, but should be stable by the end of the month.
